#pragma once

#include <string>
#include <vector>

using namespace std;

vector<pair<string, unsigned long>> knownAddons = vector<pair<string, unsigned long>>
{
	pair<string, unsigned long>("Armour", 0x50),
	pair<string, unsigned long>("Cloak", 0x51),
	pair<string, unsigned long>("Recharge unit", 0x52),
	pair<string, unsigned long>("Faraday cage", 0x53),
	pair<string, unsigned long>("Scavanger unit", 0x54),
	pair<string, unsigned long>("Shield", 0x56),
	pair<string, unsigned long>("Soulcatcher unit", 0x57),
	pair<string, unsigned long>("Repair unit", 0x58),
	pair<string, unsigned long>("Carrier guns??", 0x59)
};

vector<pair<string, unsigned long>> knownSouls = vector<pair<string, unsigned long>>
{
	pair<string, unsigned long>("BORDEN", 0x180),
	pair<string, unsigned long>("VANKIN", 0x181),
	pair<string, unsigned long>("CLUTE", 0x182),
	pair<string, unsigned long>("ELROY", 0x183),
	pair<string, unsigned long>("KOROLEV", 0x184),
	pair<string, unsigned long>("LAZARE", 0x185),
	pair<string, unsigned long>("KENZIE", 0x186),
	pair<string, unsigned long>("KROKER", 0x187),
	pair<string, unsigned long>("MADSEN", 0x188),
	pair<string, unsigned long>("KROKER", 0x187),
	pair<string, unsigned long>("PATTON", 0x189),
	pair<string, unsigned long>("RANSOM", 0x18a),
	pair<string, unsigned long>("SINCLAIR", 0x18b),
	pair<string, unsigned long>("DRONE", 0x18c),
	pair<string, unsigned long>("PLAYER", 0x18d)
};

vector<string> knownWeapons = vector<string>
{
"Minigun"
,"Missile"
,"Laser"
,"LightningGun"
,"WallLaser"
,"Lobber"
,"Flamer"
,"EMP"
};

vector<string> knownObjs = vector<string>
{
"None"
,"OakTree"
,"LeafyTree"
,"TallTree"
,"TallTree2"
,"FlatBush"
,"ThinBush"
,"BigBush"
,"LittleRock"
,"MediumRock"
,"TallRock"
,"SuperTank"
,"Chopper"
,"SuperChopper"
,"Lifter"
,"dedicatedLifter"
,"Bomber"
,"Harvester"
,"HeavyTank"
,"HoverTank"
,"SuperHover"
,"StaticPlatform"
,"Carrier"
,"MutantCarrier"
,"CarrierRusty"
,"CarrierRustyLevel6"
,"DeadCarrier"
,"DeadCarrier1"
,"ReconBuggy"
,"AlienTower"
,"AlienWallSection"
,"SmallFlyer"
,"MediumFlyer"
,"HoverLaser"
,"BlastTower"
,"MachineGun"
,"hymacgun"
,"Howitzer"
,"hybrid_Howitzer"
,"Node"
,"FinalNode"
,"BubbleCopter"
,"Apache"
,"M1Tank"
,"MammothTank"
,"MobileHowitzer"
,"CabalBomber"
,"hybrid_chopper"
,"hybrid_apache"
,"M1_Hybrid"
,"hybridmamtank"
,"mobhybhow"
,"hybrid_vtol"
,"CannonBunker"
,"hybunker"
,"LightWalker"
,"TinyWalker"
,"HeavyWalker"
,"SiegeSlug"
,"Digger1"
,"Logger1"
,"Plough1"
,"l3truck"
,"10ton"
,"All_terrain"
,"submarine"
,"Truck1"
,"TruckTanker1"
,"TruckContainer1"
,"L15Boss"
,"CargoPlane"
,"*BrainPod"
,"*CultureClub"
,"comdish"
,"*comdish2"
,"workinggun"
,"hybrid_aa_gun"
,"Alienackackgun"
,"Rustygun1"
,"Rustygun2"
,"Rustygun3"
,"l2chopperdown"
,"MissilePlatfrom"
,"HeavyTankRescue"
,"HoverTankRescue"
,"train_engine"
,"train_car"
,"train_tanker"
,"MaglevTrain1"
,"ML_straight"
,"ML_shortstraight"
,"ML_points1"
,"ML_points2"
,"rails_points"
,"rails_points_a"
,"rails_short"
,"rails_no_support"
,"train_entrance01"
,"rail_crossing"
,"rails_buffers"
,"flyprod"
,"hyflyprod"
,"AlienProdTower"
,"groundprod"
,"hybrid_GP"
,"ALIENGROUNDPROD"
,"largeprod"
,"hylargeprod"
,"ALIENLARGEPROD"
,"Maggot"
,"command"
,"hybridcommand"
,"ALIENCOMCENTER"
,"powerstore"
,"hybrid_store"
,"alienpowerstore"
,"l4oilpump"
,"hyenergyprod"
,"ALIENPUMP"
,"radar"
,"criticalradar"
,"spytower"
,"alienspytower"
,"transmitter"
,"criticaltransmitter"
,"recharge_crate"
,"chinock"
,"blobman"
,"l7blobman"
,"Seagull"
,"FlockOfAliens"
,"MapRevealer1"
,"MapRevealer2"
,"MapRevealer3"
,"coldgenerator"
,"SCAVHarvester"
,"REPAIRHarvester"
,"SCAVSuperTank"
,"REPAIRSuperTank"
,"commtower"
,"mine"
,"Camera1"
,"Camera2"
,"Camera3"
,"Camera4"
,"Camera5"
,"Camera6"
,"Camera7"
,"Camera8"
,"Camera9"
,"Camera10"
,"Camera11"
,"Camera12"
,"CamTarget1"
,"CamTarget2"
,"CamTarget3"
,"CamTarget4"
,"CamTarget5"
,"CamTarget6"
,"CamTarget7"
,"CamTarget8"
,"CamTarget9"
,"CamTarget10"
,"CamTarget11"
,"CamTarget12"
,"RotCamera1"
,"RotCamera2"
,"RotCamera3"
,"RotCamera4"
,"RotCamera5"
,"RotCamera6"
,"RotCamera7"
,"RotCamera8"
,"Chatest"
,"chatstatue"
,"scavtank"
,"Missile_Silo"
,"blastdoors"
,"hybriddoor"
,"ltenhbasedoor"
,"ltendefdoor"
,"ltenpowerplant"
,"clamp1"
,"clamp2"
,"clamp3"
,"clamp4"
,"welder1"
,"welder2"
,"welder3"
,"welder4"
,"10xcliff"
,"10xcliff2"
,"diagonal_cliff"
,"diagonal_cliff2"
,"shield-unit"
,"lasercrate"
,"SolidSimploids"
,"striplight"
,"disa_gun"
,"areamarker"
,"waypointmarker"
,"rallypoint"
,"center"
,"sphere"
,"vane"
,"Basedoor"
};